export const 
THUMB_CHECK = 'THUMB_CHECK',
THUMB_SUBMITTED = 'THUMB_SUBMITTED',
BEGIN_THUMBCHECK = 'BEGIN_THUMBCHECK',
HIDE_MODAL = 'HIDE_MODAL',
OPEN_MODAL = 'OPEN_MODAL',
THUMB_RESULT = 'THUMB_RESULT',
THUMB_RESET = 'THUMB_RESET';

