export const QUESTION_MODAL_SHOW = 'QUESTION_MODAL_SHOW';
export const QUESTION_MODAL_HIDE = 'QUESTION_MODAL_HIDE';
export const QUESTION_MODAL_ADD_USER = 'QUESTION_MODAL_ADD_USER';
export const QUESTION_MODAL_ADD_USERS = 'QUESTION_MODAL_ADD_USERS';
export const QUESTION_MODAL_DEQUEUE = 'QUESTION_MODAL_DEQUEUE';
