export const STUDENT_CALL_STUDENT = 'STUDENT_CALL_STUDENT';
export const TEACHER_SELECT_STUDENT_VIDEO = 'TEACHER_SELECT_STUDENT_VIDEO';
export const ADD_VIDEO_SESSION = 'ADD_VIDEO_SESSION';
export const ADD_PHONE_FROM_WINDOW = "ADD_PHONE_FROM_WINDOW";

