export const USER_CALL_USER = 'USER_CALL_USER';
export const TEACHER_SELECT_STUDENT_VIDEO = 'TEACHER_SELECT_STUDENT_VIDEO';
export const ADD_VIDEO_SESSION = 'ADD_VIDEO_SESSION';
export const ADD_CLASS_VIDEO_SESSION = 'ADD_CLASS_VIDEO_SESSION';
export const EMIT_TEACHER_VIDEO_SESSION = 'EMIT_TEACHER_VIDEO_SESSION';


export const GET_USER_VIDEO = 'GET_USER_VIDEO';
export const MAKE_CALL = 'MAKE_CALL';
