export const STUDENT_CALL_STUDENT = 'STUDENT_CALL_STUDENT';
export const TEACHER_SELECT_STUDENT_VIDEO = 'TEACHER_SELECT_STUDENT_VIDEO';


// export const QUIZ_REJECT = 'QUIZ_REJECT';

// export const DRAWER_SHOW = 'DRAWER_SHOW';
// export const DRAWER_HIDE = 'DRAWER_HIDE';
// export const DRAWER_DISPLAY = 'DRAWER_DISPLAY';

// export const USER_LOGIN = 'USER_LOGIN';
// export const USER_JOINED_CLASS = 'USER_JOINED_CLASS';
// export const USER_LEFT_CLASS = 'USER_LEFT_CLASS';

