export const 
QUIZ_FETCH = 'QUIZ-FETCH', 
ADD_QUIZFORM = 'ADD_QUIZFORM', 
ANSWER_QUESTION = 'ANSWER_QUESTION', 
START_QUIZ = 'START_QUIZ', 
ALL_QUIZZES = 'ALL_QUIZZES', 
EDIT_QUIZ = 'EDIT_QUIZ', 
UPDATE_QUIZ = 'UPDATE_QUIZ', 

STORE_QUIZ = 'STORE_QUIZ',
QUIZ_SUBMISSION = 'QUIZ-SUBMISSION', 

DISPLAY_RESULTS = 'DISPLAY_RESULTS', 
BEGIN_QUIZ = 'BEGIN_QUIZ',

OPEN_STUDENT_MODAL = 'OPEN_STUDENT_MODAL', 
OPEN_TEACHER_MODAL = 'OPEN_TEACHER_MODAL', 

CLOSE_STUDENT_MODAL = 'CLOSE_STUDENT_MODAL', 
CLOSE_TEACHER_MODAL = 'CLOSE_TEACHER_MODAL',
END_QUIZ = 'END_QUIZ',

ERROR_MESSAGE = 'ERROR_MESSAGE';
