/* teacher actions */
export const 
/* teacher creating a quiz */
ADD_QUESTION_IN_CREATOR = 'ADD_QUESTION_IN_CREATOR', 
UPDATE_QUESTION_IN_CREATOR = 'UPDATE_QUESTION_IN_CREATOR', 

/* teacher editing a quiz */
QUIZ_SUCCESSFULLY_SAVED = 'QUIZ_SUCCESSFULLY_SAVED',
LOAD_QUIZ_IN_EDITOR = 'LOAD_QUIZ_IN_EDITOR',
UPDATE_QUIZ_IN_EDITOR = 'UPDATE_QUIZ_IN_EDITOR',
ADD_QUESTION_IN_EDITOR = 'ADD_QUESTION_IN_EDITOR', 
UPDATE_TITLE_IN_EDITOR = 'UPDATE_TITLE_IN_EDITOR',

/* teacher in quiz modal */
OPEN_TEACHER_MODAL = 'OPEN_TEACHER_MODAL', 
CLOSE_TEACHER_MODAL = 'CLOSE_TEACHER_MODAL',
FETCH_QUIZ_LIST = 'FETCH_QUIZ_LIST',
DISPLAY_RESULTS_FROM_QUIZ = 'DISPLAY_RESULTS_FROM_QUIZ', 
DELETE_QUIZ = 'DELETE_QUIZ',
QUIZ_SENT_TO_STUDENTS= 'QUIZ_SENT_TO_STUDENTS',

/* student actions */
STORE_QUIZ = 'STORE_QUIZ',
ANSWER_QUESTION = 'ANSWER_QUESTION', 
QUIZ_FETCH = 'QUIZ-FETCH', 
END_QUIZ = 'END_QUIZ',
ERROR_MESSAGE = 'ERROR_MESSAGE',
OPEN_STUDENT_MODAL = 'OPEN_STUDENT_MODAL', 
CLOSE_STUDENT_MODAL = 'CLOSE_STUDENT_MODAL'; 
