export const QUIZ_SUBMISSION = 'QUIZ-SUBMISSION';
export const QUIZ_FETCH = 'QUIZ-FETCH';
export const ADD_QUIZFORM = 'ADD_QUIZFORM';
export const UPDATE_QUIZ = 'UPDATE_QUIZ';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const START_QUIZ = 'START_QUIZ';
export const ALL_QUIZZES = 'ALL_QUIZZES';