export const QUIZ_ACCEPT = 'QUIZ_ACCEPT';
export const QUIZ_REJECT = 'QUIZ_REJECT';

export const DRAWER_SHOW = 'DRAWER_SHOW';
export const DRAWER_HIDE = 'DRAWER_HIDE';
export const DRAWER_DISPLAY = 'DRAWER_DISPLAY';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_JOINED_CLASS = 'USER_JOINED_CLASS';
export const USER_LEFT_CLASS = 'USER_LEFT_CLASS';

export const USER_VIDEO_MODAL_SHOW = 'USER_VIDEO_MODAL_SHOW';
export const USER_VIDEO_MODAL_HIDE = 'USER_VIDEO_MODAL_HIDE';

export const SERVER_URL = 'http://192.168.1.40:8000';

export const SELECT_USER = 'SELECT_USER';

